import 'bootstrap/dist/css/bootstrap.css';
import './global.css';

export const metadata = {
  title: 'Welcome to apps/home',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <div className="container">{children}</div>
      </body>
    </html>
  );
}
