import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Company Product Listing",
  description: "Generated by create next app",
};

export default async function CompanyHomeLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="container">
      <div className="row">
        <div className="col-md-4 col-12">Filters</div>
        <div className="col-md-8 col-12">{children}</div>
      </div>
    </div>
  );
}
