import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const getNavbar = async () => {
  const res = await fetch("http://localhost:8000/navbar/");
  return res.json();
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  let navbarResponse = await getNavbar();
  console.log(navbarResponse);

  return (
    <html lang="en">
      <body className={inter.className}>
        <div dangerouslySetInnerHTML={{ __html: navbarResponse.html }}></div>
        {children}
      </body>
    </html>
  );
}
